### ISSUE TITLE
Suggestions on Attacker API

### ISSUE THREAD

**Issue by AntoineToussaint** [microprediction/endersgame#1]
Separation of concerns:

- "tick": this is the Attacker receiving a new data point. Given the nature of network, there is no reason that two data points sent in on order from the backend are received in the same order in the client.
Suggest adding time to the value.
To make dealing with multivariate timeseries, an ID is also convenient.
So an API would look like `receive(pt: Point)` where `Point` is {ID, time, value}.

- "predict": this is the prediction API and could be called independent of data being received by the Attacker. Say something doesn't tick anymore, we may still want to know an updated prediction. This is the typical case of liquid vs illiquid timeseries where prediction without tick will be updated by the other one ticking.
Also, would need a time, and not an index for horizon.

The "fit" shouldn't really be part of the API as the client should be responsible if/when to fit their model.

**Comment by microprediction** [comment]
Good suggestion. Accepted.

**Comment by microprediction** [comment]
acceptede
